from typing import Dict, Any
from pydantic import Field
from pydantic_settings import BaseSettings, SettingsConfigDict

class Settings(BaseSettings):
    """Global configuration settings for IDIP."""
    
    model_config = SettingsConfigDict(
        env_file=".env",
        env_file_encoding="utf-8",
        extra="ignore"
    )

    CHUNK_SIZE: int = Field(default=512, description="RAG chunk size in tokens")
    CHUNK_OVERLAP: int = Field(default=64, description="Overlap between chunks in tokens")
    TOP_K_RETRIEVAL: int = Field(default=10, description="Number of top retrieved documents")
    RERANKER_THRESHOLD: float = Field(default=0.4, description="Similarity threshold for cross-encoder reranker")
    ENSEMBLE_WEIGHTS: Dict[str, float] = Field(
        default_factory=lambda: {"llm": 0.5, "ner": 0.25, "classifier": 0.25},
        description="Weight distribution for ensemble model results"
    )
    MODEL_TEMPERATURE: float = Field(default=0.2, description="LLM generation temperature")
    MAX_TOKENS: int = Field(default=1024, description="Maximum new tokens generated by LLM")
    CONFIDENCE_THRESHOLD: float = Field(default=0.75, description="Response confidence threshold")
    DRIFT_ALERT_THRESHOLD: float = Field(default=0.15, description="PSI alert threshold for feature drift detection")
    CACHE_TTL: int = Field(default=3600, description="Time-to-live for cache in seconds")
    BATCH_SIZE: int = Field(default=32, description="Inference batch size")
    AUTOSCALE_MIN_REPLICAS: int = Field(default=2, description="Minimum number of Kubernetes pod replicas")
    VECTOR_DB_PROVIDER: str = Field(default="pinecone", description="Vector database provider (pinecone, weaviate, or faiss)")
    EMBEDDING_MODEL: str = Field(default="BAAI/bge-large-en-v1.5", description="Embedding model name")
    LLM_MODEL: str = Field(default="mistralai/Mistral-7B-Instruct-v0.2", description="LLM model name")
    ENVIRONMENT: str = Field(default="development", description="Deployment environment (development, staging, or production)")

    # Database and Caching settings
    POSTGRES_USER: str = Field(default="postgres")
    POSTGRES_PASSWORD: str = Field(default="postgres")
    POSTGRES_DB: str = Field(default="idip_metadata")
    POSTGRES_HOST: str = Field(default="localhost")
    POSTGRES_PORT: int = Field(default=5432)
    REDIS_HOST: str = Field(default="localhost")
    REDIS_PORT: int = Field(default=6379)
