apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "idip.fullname" . }}-config
  labels:
    {{- include "idip.labels" . | nindent 4 }}
data:
  ENVIRONMENT: {{ .Values.environment | quote }}
  {{- range $key, $value := .Values.config }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
