{{- if .Values.autoscaling.enabled -}}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "idip.fullname" . }}-api-hpa
  labels:
    {{- include "idip.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "idip.fullname" . }}-api
  minReplicas: {{ .Values.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.autoscaling.maxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.autoscaling.targetMemoryUtilizationPercentage }}
---
{{- if .Values.autoscaling.customMetrics.celeryQueueDepth.enabled -}}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "idip.fullname" . }}-worker-hpa
  labels:
    {{- include "idip.labels" . | nindent 4 }}
    app.kubernetes.io/component: worker
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "idip.fullname" . }}-worker
  minReplicas: {{ .Values.replicaCount.worker }}
  maxReplicas: {{ .Values.autoscaling.maxReplicas }}
  metrics:
    - type: External
      external:
        metric:
          name: {{ .Values.autoscaling.customMetrics.celeryQueueDepth.metricName }}
        target:
          type: Value
          averageValue: {{ .Values.autoscaling.customMetrics.celeryQueueDepth.targetValue }}
{{- end }}
{{- end }}
